name: CD Pipeline - Deploy Flask App to AWS EC2

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH into EC2 and Deploy Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling latest Docker image from DockerHub....."
            docker stop bank-marketing-predictor || true
            docker rm bank-marketing-predictor || true
            docker pull niwanthi/bank-marketing-predictor:latest
            echo "Starting new container...."
            docker run -d -p 5000:5000 --name bank-marketing-predictor niwanthi/bank-marketing-predictor:latest
